#!/bin/sh

# Make an app icon from pngs.

cd src/images

# Original PNG file, should be 512x512 pixels or larger.
ORIGINAL='tint-fullsize.png'

# Name of iconset folder.
OUTPUT='Tint.iconset'

mkdir $OUTPUT

sips -z 16 16     $ORIGINAL --out $OUTPUT/icon_16x16.png
sips -z 32 32     $ORIGINAL --out $OUTPUT/icon_16x16@2x.png
sips -z 32 32     $ORIGINAL --out $OUTPUT/icon_32x32.png
sips -z 64 64     $ORIGINAL --out $OUTPUT/icon_32x32@2x.png
sips -z 128 128   $ORIGINAL --out $OUTPUT/icon_128x128.png
sips -z 256 256   $ORIGINAL --out $OUTPUT/icon_128x128@2x.png
sips -z 256 256   $ORIGINAL --out $OUTPUT/icon_256x256.png
sips -z 512 512   $ORIGINAL --out $OUTPUT/icon_256x256@2x.png
sips -z 512 512   $ORIGINAL --out $OUTPUT/icon_512x512.png

cp $ORIGINAL $OUTPUT/icon_512x512@2x.png

iconutil -c icns $OUTPUT

rm -R $OUTPUT
